# fly.toml app configuration file generated for digital-kabootar-kargil on 2026-07-14T08:46:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'digital-kabootar-kargil'
primary_region = 'ams'

[build]

[env]
  DATABASE_PATH = '/data/kabootar.db'
  PORT = '3000'
  REQUIRE_HUMAN_REVIEW = 'false'

[[mounts]]
  source = 'kabootar_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
